# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: npm i
    command: npm start
  - name: Postgres dev database
    init: docker pull postgres
    command: docker run --name postgresql-container -p 5432:5432 -e POSTGRES_PASSWORD=devPassword -d postgres
